version : '3.8'

networks:
  basic:
    name: "basic"

services:
  goweb:
    container_name: test
    image: nunu-test/demo-api:v1
    environment:
      - APP_CONF=config/local.yml
    volumes:
      - ./config/local.yml:/data/app/config/local.yml
    ports:
      - 8080:8000
    networks:
      - basic
