env: local
http:
  port: 8000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  mysql:
    user: root:123456@tcp(192.168.58.131:3306)/basic?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.58.131:6379
    password: "123456"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
